"""Storage Protocols: narrow, intention-revealing methods, no leaking SQL types.

Every method takes and returns core/ domain objects or primitives. This is the
seam that keeps hosting and the backend swappable (PRD 8.6); one concrete
implementation lives in adapters/pg/.
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import date, datetime
from typing import Protocol

from jazz_agent.core.models import (
    Artist,
    Club,
    Feedback,
    MatchMiss,
    MbArtist,
    MbArtistEdge,
    MbLookupMiss,
    Performer,
    PlaylistEvent,
    PlaylistTrack,
    RunLogEntry,
    Show,
    WeekPlaylist,
)


class ClubRepo(Protocol):
    def get_active_clubs(self) -> list[Club]: ...
    def get_club(self, club_id: str) -> Club | None: ...


class ShowRepo(Protocol):
    def upsert_show(self, show: Show) -> int:
        """Insert, or on a (club_id, show_date, act_name_norm) conflict update
        last_seen_at rather than inserting a duplicate. Returns show_id."""
        ...

    def get_show(self, show_id: int) -> Show | None: ...
    def record_performers(self, show_id: int, performers: Sequence[Performer]) -> None: ...
    def performers_for_show(self, show_id: int) -> list[Performer]: ...
    def record_match_miss(self, miss: MatchMiss) -> None: ...
    def match_misses_for_show(self, show_id: int) -> list[MatchMiss]: ...


class ArtistRepo(Protocol):
    def upsert_artist(self, artist: Artist) -> None: ...
    def get_artist(self, spotify_artist_id: str) -> Artist | None: ...
    def link_show_artist(self, show_id: int, spotify_artist_id: str) -> None: ...
    def artists_for_show(self, show_id: int) -> list[Artist]: ...


class GraphRepo(Protocol):
    def upsert_mb_artist(self, artist: MbArtist) -> None: ...
    def get_mb_artist(self, mbid: str) -> MbArtist | None: ...
    def record_edges(self, edges: Sequence[MbArtistEdge]) -> None: ...
    def edges_for(self, mbid: str) -> list[MbArtistEdge]: ...
    def record_lookup_miss(self, miss: MbLookupMiss) -> None: ...
    def get_lookup_miss(self, name_norm: str) -> MbLookupMiss | None: ...


class PlaylistRepo(Protocol):
    def upsert_week_playlist(self, playlist: WeekPlaylist) -> int:
        """Insert, or update title/description, on a (club_id, week_start_date)
        conflict. Returns the row's id. spotify_playlist_id/url are untouched by
        this call -- they are usually not known yet; see link_spotify_playlist."""
        ...

    def link_spotify_playlist(
        self, week_playlist_id: int, spotify_playlist_id: str, spotify_url: str
    ) -> None: ...
    def get_week_playlist(self, club_id: str, week_start_date: date) -> WeekPlaylist | None: ...
    def add_tracks(self, week_playlist_id: int, tracks: Sequence[PlaylistTrack]) -> None: ...
    def remove_track(self, week_playlist_id: int, spotify_track_id: str) -> None: ...
    def tracks_for(self, week_playlist_id: int) -> list[PlaylistTrack]: ...
    def record_event(self, event: PlaylistEvent) -> None: ...
    def events_for(self, week_playlist_id: int) -> list[PlaylistEvent]: ...
    def mark_removed(self, week_playlist_id: int, removed_at: datetime) -> None: ...


class FeedbackRepo(Protocol):
    def record_feedback(self, feedback: Feedback) -> int: ...
    def feedback_for_target(self, target_type: str, target_id: str) -> list[Feedback]: ...


class RunRepo(Protocol):
    def log_run_outcome(self, entry: RunLogEntry) -> None: ...
    def recent_runs(self, club_id: str | None = None, days: int = 7) -> list[RunLogEntry]: ...
