"""Regenerate the MCP tool inventory in docs/claude-project-instructions.md
from the live FastMCP registry (ADR-016). Rewrites only the content between
the BEGIN/END GENERATED TOOL INVENTORY markers; everything outside them is
hand-maintained policy prose and is preserved byte-for-byte.

The predictable failure this exists to prevent: a tool added in month three
while the pasted Project instructions still describe the old set, so the new
tool is never called. Generating the inventory makes that impossible rather
than merely unlikely.
"""

from __future__ import annotations

import asyncio
import dataclasses
import re
import sys
from pathlib import Path
from typing import Any

from jazz_agent.config import load_config
from jazz_agent.mcp.server import build_server

DOCS_PATH = Path(__file__).resolve().parent.parent / "docs" / "claude-project-instructions.md"
BEGIN_MARKER = "<!-- BEGIN GENERATED TOOL INVENTORY -->"
END_MARKER = "<!-- END GENERATED TOOL INVENTORY -->"

# record_feedback is this server's only write tool; everything else is a read.
_WRITE_TOOLS = {"record_feedback"}


def _signature(name: str, schema: dict[str, Any]) -> str:
    required = set(schema.get("required", []))
    params = [
        param_name if param_name in required else f"{param_name}?"
        for param_name in schema.get("properties", {})
    ]
    return f"{name}({', '.join(params)})"


def render_tool_inventory(tools: Any) -> str:
    """Pure formatting: a Sequence of objects with .name/.description/.parameters
    (fastmcp Tool, or anything duck-typed the same way) to markdown."""
    reads = sorted((t for t in tools if t.name not in _WRITE_TOOLS), key=lambda t: t.name)
    writes = sorted((t for t in tools if t.name in _WRITE_TOOLS), key=lambda t: t.name)

    lines = [
        BEGIN_MARKER,
        "### Available tools",
        "",
        "*Generated by `make project-instructions`. Do not edit by hand.*",
        "",
        "**Reads**",
        "",
    ]
    for tool in reads:
        description = " ".join((tool.description or "").split())
        lines.append(f"- `{_signature(tool.name, tool.parameters)}` -- {description}")
    lines += ["", "**Writes**", ""]
    for tool in writes:
        description = " ".join((tool.description or "").split())
        lines.append(f"- `{_signature(tool.name, tool.parameters)}` -- {description}")
    lines += ["", END_MARKER]
    return "\n".join(lines)


def _live_tools() -> Any:
    config = load_config()
    # build_server() never touches pool/music at registration time -- only
    # inside the tool bodies, which this script never calls -- so None is
    # safe here. A placeholder base_url avoids needing real deployment
    # config (a public MCP_PUBLIC_URL) just to list tool names.
    base_url = config.mcp_public_url or "https://placeholder.invalid"
    config_for_generation = dataclasses.replace(config, mcp_public_url=base_url)
    server = build_server(config_for_generation, None, None)  # type: ignore[arg-type]

    # The public list_tools()/get_tool() apply each tool's own auth= check,
    # which always evaluates false outside a real authenticated request, so
    # every tool would vanish from the list. _list_tools() is the unfiltered
    # internal registry, which is exactly what a doc generator needs.
    return asyncio.run(server._list_tools())  # noqa: SLF001


def main() -> int:
    original = DOCS_PATH.read_text()
    pattern = re.compile(re.escape(BEGIN_MARKER) + r".*?" + re.escape(END_MARKER), re.DOTALL)
    if not pattern.search(original):
        print(f"Markers not found in {DOCS_PATH}", file=sys.stderr)
        return 1

    updated = pattern.sub(lambda _match: render_tool_inventory(_live_tools()), original)
    DOCS_PATH.write_text(updated)
    print(f"Rewrote tool inventory in {DOCS_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
